/// Utilities for converting ISO 3166-1 alpha-2 country codes into
/// flag emojis and human-readable names.
///
/// Flag emojis are generated via Unicode regional-indicator arithmetic —
/// no external package required.
abstract final class CountryUtils {
  /// Returns the flag emoji for a 2-letter country code (e.g. 'FR' → '🇫🇷').
  /// Returns '🌍' for unknown / invalid codes.
  static String flag(String code) {
    if (code.length != 2) return '🌍';
    final upper = code.toUpperCase();
    final a = upper.codeUnitAt(0) - 65; // 'A' = 65
    final b = upper.codeUnitAt(1) - 65;
    if (a < 0 || a > 25 || b < 0 || b > 25) return '🌍';
    const base = 0x1F1E6; // Regional Indicator Symbol Letter A
    return String.fromCharCode(base + a) + String.fromCharCode(base + b);
  }

  /// Returns the localised (French) country name for the given code.
  /// Falls back to the uppercased code if unknown.
  static String name(String code) {
    return _names[code.toUpperCase()] ?? code.toUpperCase();
  }

  /// Returns '🇫🇷 France' style string.
  static String flagAndName(String code) => '${flag(code)} ${name(code)}';

  static const Map<String, String> _names = {
    'AD': 'Andorre',
    'AE': 'Émirats arabes unis',
    'AF': 'Afghanistan',
    'AG': 'Antigua-et-Barbuda',
    'AL': 'Albanie',
    'AM': 'Arménie',
    'AO': 'Angola',
    'AR': 'Argentine',
    'AT': 'Autriche',
    'AU': 'Australie',
    'AZ': 'Azerbaïdjan',
    'BA': 'Bosnie-Herzégovine',
    'BB': 'Barbade',
    'BD': 'Bangladesh',
    'BE': 'Belgique',
    'BF': 'Burkina Faso',
    'BG': 'Bulgarie',
    'BH': 'Bahreïn',
    'BI': 'Burundi',
    'BJ': 'Bénin',
    'BN': 'Brunéi',
    'BO': 'Bolivie',
    'BR': 'Brésil',
    'BS': 'Bahamas',
    'BT': 'Bhoutan',
    'BW': 'Botswana',
    'BY': 'Biélorussie',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CD': 'Congo (RDC)',
    'CF': 'République centrafricaine',
    'CG': 'Congo',
    'CH': 'Suisse',
    'CI': "Côte d'Ivoire",
    'CL': 'Chili',
    'CM': 'Cameroun',
    'CN': 'Chine',
    'CO': 'Colombie',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CV': 'Cap-Vert',
    'CY': 'Chypre',
    'CZ': 'Tchéquie',
    'DE': 'Allemagne',
    'DJ': 'Djibouti',
    'DK': 'Danemark',
    'DM': 'Dominique',
    'DO': 'République dominicaine',
    'DZ': 'Algérie',
    'EC': 'Équateur',
    'EE': 'Estonie',
    'EG': 'Égypte',
    'ER': 'Érythrée',
    'ES': 'Espagne',
    'ET': 'Éthiopie',
    'FI': 'Finlande',
    'FJ': 'Fidji',
    'FM': 'Micronésie',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'Royaume-Uni',
    'GD': 'Grenade',
    'GE': 'Géorgie',
    'GH': 'Ghana',
    'GM': 'Gambie',
    'GN': 'Guinée',
    'GQ': 'Guinée équatoriale',
    'GR': 'Grèce',
    'GT': 'Guatemala',
    'GW': 'Guinée-Bissau',
    'GY': 'Guyana',
    'HN': 'Honduras',
    'HR': 'Croatie',
    'HT': 'Haïti',
    'HU': 'Hongrie',
    'ID': 'Indonésie',
    'IE': 'Irlande',
    'IL': 'Israël',
    'IN': 'Inde',
    'IQ': 'Irak',
    'IR': 'Iran',
    'IS': 'Islande',
    'IT': 'Italie',
    'JM': 'Jamaïque',
    'JO': 'Jordanie',
    'JP': 'Japon',
    'KE': 'Kenya',
    'KG': 'Kirghizistan',
    'KH': 'Cambodge',
    'KI': 'Kiribati',
    'KM': 'Comores',
    'KN': 'Saint-Kitts-et-Nevis',
    'KP': 'Corée du Nord',
    'KR': 'Corée du Sud',
    'KW': 'Koweït',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LB': 'Liban',
    'LC': 'Sainte-Lucie',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Libéria',
    'LS': 'Lesotho',
    'LT': 'Lituanie',
    'LU': 'Luxembourg',
    'LV': 'Lettonie',
    'LY': 'Libye',
    'MA': 'Maroc',
    'MC': 'Monaco',
    'MD': 'Moldavie',
    'ME': 'Monténégro',
    'MG': 'Madagascar',
    'MH': 'Îles Marshall',
    'MK': 'Macédoine du Nord',
    'ML': 'Mali',
    'MM': 'Myanmar',
    'MN': 'Mongolie',
    'MR': 'Mauritanie',
    'MT': 'Malte',
    'MU': 'Maurice',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexique',
    'MY': 'Malaisie',
    'MZ': 'Mozambique',
    'NA': 'Namibie',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Pays-Bas',
    'NO': 'Norvège',
    'NP': 'Népal',
    'NR': 'Nauru',
    'NZ': 'Nouvelle-Zélande',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Pérou',
    'PG': 'Papouasie-Nouvelle-Guinée',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Pologne',
    'PT': 'Portugal',
    'PW': 'Palaos',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RO': 'Roumanie',
    'RS': 'Serbie',
    'RU': 'Russie',
    'RW': 'Rwanda',
    'SA': 'Arabie saoudite',
    'SB': 'Îles Salomon',
    'SC': 'Seychelles',
    'SD': 'Soudan',
    'SE': 'Suède',
    'SG': 'Singapour',
    'SI': 'Slovénie',
    'SK': 'Slovaquie',
    'SL': 'Sierra Leone',
    'SM': 'Saint-Marin',
    'SN': 'Sénégal',
    'SO': 'Somalie',
    'SR': 'Suriname',
    'SS': 'Soudan du Sud',
    'ST': 'São Tomé-et-Príncipe',
    'SV': 'Salvador',
    'SY': 'Syrie',
    'SZ': 'Eswatini',
    'TD': 'Tchad',
    'TG': 'Togo',
    'TH': 'Thaïlande',
    'TJ': 'Tadjikistan',
    'TL': 'Timor oriental',
    'TM': 'Turkménistan',
    'TN': 'Tunisie',
    'TO': 'Tonga',
    'TR': 'Turquie',
    'TT': 'Trinité-et-Tobago',
    'TV': 'Tuvalu',
    'TZ': 'Tanzanie',
    'UA': 'Ukraine',
    'UG': 'Ouganda',
    'US': 'États-Unis',
    'UY': 'Uruguay',
    'UZ': 'Ouzbékistan',
    'VA': 'Vatican',
    'VC': 'Saint-Vincent-et-les-Grenadines',
    'VE': 'Venezuela',
    'VN': 'Viêt Nam',
    'VU': 'Vanuatu',
    'WS': 'Samoa',
    'YE': 'Yémen',
    'ZA': 'Afrique du Sud',
    'ZM': 'Zambie',
    'ZW': 'Zimbabwe',
  };
}
